name: linting, testing, building
on: 
    push:
        branches: [ main ]
    pull_request: 
        branches: [ main ]
jobs: 
    lint: 
        runs-on: ubuntu-latest
        strategy: 
            matrix:
                node_version: [17.x, 18.x]
                
        steps: 
            - uses: actions/checkout@v2
            - name: Staring NodeJS ${{matrix.node_version}}
              uses: actions/setup-node@v1
              with: 
                 node-version: ${{matrix.node_version}}
            - name: install modules
              run: npm ci
            - name: linting typescript
              run: npm run lint:ts
            - name: linting scss
              run: npm run lint:scss
    test:
        runs-on: ubuntu-latest
        needs: lint
        strategy: 
            matrix:
                node_version: [17.x, 18.x]
            
        steps: 
            - uses: actions/checkout@v2
            - name: Staring NodeJS ${{matrix.node_version}}
              uses: actions/setup-node@v3
              with: 
                 node-version: ${{matrix.node_version}}
            - name: install modules
              run: npm ci
            - name: testing
              run: npm run test:unit
    build: 
        runs-on: ubuntu-latest
        needs: test
        strategy: 
            matrix:
                node_version: [17.x, 18.x]
            
        steps: 
            - uses: actions/checkout@v2
            - name: Staring NodeJS ${{matrix.node_version}}
              uses: actions/setup-node@v1
              with: 
                 node-version: ${{matrix.node_version}}
            - name: install modules
              run: npm ci
            - name: build
              run: npm run build:prod